import fs from 'node:fs';
import {createServer} from 'node:net';
import path from 'node:path';
import {generatePrivateKey,getPublicKey} from '@cgp/core';
import {RelayServer,LocalRelayPubSubAdapter} from '@cgp/relay/src/server';
import {LevelStore} from '@cgp/relay/src/store_level';
import {createHeliaIpfsPlugin,createMediaStoragePolicyPlugin,createEncryptionPolicyPlugin} from '@cgp/relay/src/plugins';
const output=path.resolve('output/community-continuity',`local-app-media-${Date.now()}`);fs.mkdirSync(output,{recursive:true});
const keys=Array.from({length:4},()=>generatePrivateKey());
const quorum={epoch:path.basename(output),members:keys.slice(0,3).map(getPublicKey),requiredVotes:2,voteTimeoutMs:4000};
let roomRelay:any;
const bus=new LocalRelayPubSubAdapter(),relays:Array<RelayServer|undefined>=[],ports:number[]=[];
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function start(i:number){
 if(!ports[i])ports[i]=await new Promise<number>((resolve,reject)=>{const probe=createServer();probe.once('error',reject);probe.listen(0,'127.0.0.1',()=>{const port=(probe.address() as any).port;probe.close(()=>resolve(port));});});
 const plugins=[createHeliaIpfsPlugin({id:'helia',gatewayUrl:`http://127.0.0.1:${ports[i]}/plugins/cgp.ipfs.helia/ipfs/{cid}`,storeDir:path.join(output,`helia-${i}`),mode:'local',autoStart:true,useDefaultBootstrap:false,enableDht:false,enableBitswap:false,enableTrustlessGateway:false,provideOnAdd:false,maxAddBytes:4*1024*1024}),createMediaStoragePolicyPlugin({maxAttachmentBytes:4*1024*1024,providers:[{id:'private-helia',kind:'ipfs',ipfsBackendId:'helia',priority:100,maxBytes:4*1024*1024,acceptsMimeTypes:['application/octet-stream'],adult:'allow'}]}),createEncryptionPolicyPlugin({requireEncryptedPrivateGuildMessages:true,allowEncryptedMessages:true})];
 if(roomRelay)plugins.push({name:'hollow-relay',onHttp:async(args:any)=>{const snapshot=roomRelay.snapshot();const relay={...snapshot,provider:'local-fixture',publicWsUrl:snapshot.localWsUrl,healthy:true,transport:'hollow-room'};const route=args.pathSegments[1];if(!['local','relays'].includes(route))return false;args.res.setHeader('Content-Type','application/json');args.res.end(JSON.stringify(route==='relays'?{relays:[relay]}:{enabled:true,relay}));return true;}} as any);
 relays[i]=new RelayServer(ports[i]||0,new LevelStore(path.join(output,`store-${i}`)),plugins,{listenHost:'127.0.0.1',enableDefaultPlugins:false,sequencerConsensus:false,writeQuorum:i<3?quorum:false,relayPrivateKeyHex:Buffer.from(keys[i]).toString('hex'),pubSubAdapter:bus});
 while(!relays[i]!.getPort())await pause(20);ports[i]=relays[i]!.getPort();
 for(let n=0;n<200;n++){const r=await fetch(`http://127.0.0.1:${ports[i]}/plugins/cgp.ipfs.helia/status`).catch(()=>null);if(r?.ok){const status:any=await r.json();if(status.started || status.backend?.started)return;}await pause(100);}throw Error('Helia failed to start');
}
async function main(){roomRelay=process.argv.includes('--calls')?new (await import('../../hollow-relay-plugin/src/roomRelayServer')).RoomRelayServer({host:'127.0.0.1',port:0,path:'/relay',label:'Synthetic local call fixture',requireSignedJoins:true}):undefined;await roomRelay?.start();for(let i=0;i<4;i++)await start(i);const control={commandFile:path.join(output,'command.json'),ackFile:path.join(output,'ack.json'),finishFile:path.join(output,'finish')};const receipt={ok:true,pid:process.pid,output,quorum,roomRelay:roomRelay?.snapshot(),endpoints:ports.map((port,i)=>({url:`ws://127.0.0.1:${port}`,publicKey:getPublicKey(keys[i]),mediaOnly:i===3})),control,scope:'Local real Helia UnixFS stores, no DHT/Bitswap or independent operators'};fs.writeFileSync(path.join(output,'client-window.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));let previous='';const until=Date.now()+20*60000;while(!fs.existsSync(control.finishFile)&&Date.now()<until){if(fs.existsSync(control.commandFile)){const raw=fs.readFileSync(control.commandFile,'utf8');if(raw!==previous){const c=JSON.parse(raw);if(!Number.isInteger(c.index)||c.index<0||c.index>3||!['stop','restart'].includes(c.action))throw Error('Invalid fixture control');if(relays[c.index]){await relays[c.index]!.close();relays[c.index]=undefined;}if(c.action==='restart')await start(c.index);previous=raw;fs.writeFileSync(control.ackFile,JSON.stringify({id:c.id,action:c.action,index:c.index}));}}await pause(100);}}
let failure:string|undefined;main().catch(e=>failure=e.message).finally(async()=>{await Promise.all(relays.map(r=>r?.close()));bus.close();await roomRelay?.stop();fs.writeFileSync(path.join(output,'cleanup.json'),JSON.stringify({ok:!failure,failure,pid:process.pid,ports,roomRelay:roomRelay?.snapshot(),closed:true},null,2));if(failure){console.error(JSON.stringify({failure}));process.exitCode=1;}});
